version: '3.8'

services:
  dex:
    image: ghcr.io/dexidp/dex:v2.38.0
    container_name: dex
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    ports:
      - "5556:5556"
    volumes:
      - ./dex-config.yaml:/etc/dex/config.yaml:ro
      - ./google-sa.json:/opt/google-sa.json:ro
